// <auto-generated />
using DES___Desafio_1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DES___Desafio_1.Migrations
{
    [DbContext(typeof(EmpleadosDbContext))]
    partial class EmpleadosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DES___Desafio_1.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Gestión de personal y talento humano",
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Soporte e infraestructura tecnológica",
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Gestión comercial y clientes",
                            Nombre = "Ventas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
